default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  username: multistep_form_user
  password: multistep_form_user
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: curso_development

test:
  <<: *default
  database: curso_test

production:
  <<: *default
  database: curso_production